#version 430
layout(local_size_x = 128) in;

struct Particle {
    vec2 pos;
    vec2 vel;
    vec2 acc;
    float density;
    float alpha;
    int type;
    bool isInGlass;
};

layout(std430, binding = 0) buffer ParticleBuffer {
    Particle particles[];
};

uniform float dt;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (particles[idx].type == 0) {
        particles[idx].vel += dt * particles[idx].acc;
    }
}
